### PR TITLE
Guzzle Resolver added

### PR DESCRIPTION
**Pull request by younes0**
#71

### CODE REVIEW

**Comment by younes0** [comment]
Since some Guzzle\Client configuration can't be provided by an array (subscribers as closures), I'd like to add this static method to provide my own Guzzle client instance:
```php
Embed\RequestResolvers\Guzzle::setClient($client);
```

**Comment by oscarotero** [comment]
What about set the client as a config value? Something like this:
```php
$info = Embed::create($url, [
    'resolver' => [
        'class' => 'Embed\\RequestResolvers\\Guzzle',
        'config' => [
            'client' => $client,
        ]
    ]
]);
```

**Comment by younes0** [comment]
done

**Comment by oscarotero** [comment]
Great, some considerations:

I've executed the tests usign guzzle and many of them returns this error warning:
```
49) SoundcloudTest::testTwo
Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, string given, called in /Volumes/Projects/Embed/vendor/guzzlehttp/guzzle/src/Client.php on line 88 and defined

/Volumes/Projects/Embed/vendor/guzzlehttp/guzzle/src/Client.php:127
/Volumes/Projects/Embed/vendor/guzzlehttp/guzzle/src/Client.php:88
/Volumes/Projects/Embed/src/RequestResolvers/Guzzle.php:33
/Volumes/Projects/Embed/src/RequestResolvers/Guzzle.php:33
/Volumes/Projects/Embed/src/Request.php:65
/Volumes/Projects/Embed/src/Request.php:139
/Volumes/Projects/Embed/src/Request.php:251
/Volumes/Projects/Embed/src/Adapters/File.php:43
/Volumes/Projects/Embed/src/Embed.php:96
/Volumes/Projects/Embed/src/Embed.php:28
/Volumes/Projects/Embed/tests/TestCaseBase.php:25
/Volumes/Projects/Embed/tests/SoundcloudTest.php:19
```

Currently the curl resolver prevents to load binary files (for example images, videos, pdfs, etc) here: https://github.com/oscarotero/Embed/blob/master/src/RequestResolvers/Curl.php#L179 so it only loads html documents files. This allows use url to binary files and returns the info like any other webpage without download it. Is Guzzle any option to do something similar?

Thanks

**Comment by oscarotero** [comment]
Hi, again. If you merge the latest commit in Embed in your fork, you can test the library with the guzzle resolver. All test cases use [this function](https://github.com/oscarotero/Embed/blob/master/tests/TestCaseBase.php#L28) to get the info, so you can change the function to use guzzle.

**Comment by younes0** [comment]
I'll look into the  binary files problem.

Thanks for the function. 
I'm not sure if it's the best way to include Guzzle in tests: I added this in `tests/boostrap.php`
```php
require_once __DIR__ . '/../vendor/autoload.php'; 
```
Most projects do this

**Comment by younes0** [comment]
By the way, which Guzzle version do you use? Using 5.3 latest, I did not encounter the issue you mentionned when limiting tests to Soundcloud (I do have other tests failure which happen also with the CURL resolver)

**Comment by younes0** [comment]
With latest commit, phpunit reports:

**Curl**
```php
PHPUnit 4.8.5 by Sebastian Bergmann and contributors.

...........................FF...............................F.... 65 / 72 ( 90%)
E.F....

Time: 2.46 minutes, Memory: 23.25Mb

There was 1 error:

1) ViddlerTest::testOne
Embed\Exceptions\InvalidUrlException: The url 'http://www.viddler.com/v/bdce8c7' returns the http code '0'

/www/yoda/vendor/embed/embed/src/Embed.php:48
/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:33
/www/yoda/vendor/embed/embed/tests/ViddlerTest.php:6

--

There were 4 failures:

1) ImagesBlacklistTest::testPlainText
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif
+https://avatars1.githubusercontent.com/u/377873?v=3&s=400

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/ImagesBlacklistTest.php:16

2) ImagesBlacklistTest::testPlainUrlMatch
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif
+https://avatars1.githubusercontent.com/u/377873?v=3&s=400

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/ImagesBlacklistTest.php:31

3) TwitterTest::testOmitScript
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<blockquote class="twitter-tweet"><p lang="es" dir="ltr">RT <a href="https://twitter.com/PabloHerreros">@PabloHerreros</a> Pepephone rompe la baraja - <a href="http://t.co/mFn7mcB1vy">http://t.co/mFn7mcB1vy</a></p>&mdash; pepephone (@pepephone) <a href="https://twitter.com/pepephone/status/436461
658601713664">February 20, 2014</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
+<blockquote class="twitter-tweet"><p lang="es" dir="ltr">RT <a href="https://twitter.com/PabloHerreros">@PabloHerreros</a> Pepephone rompe la baraja - <a href="http://t.co/mFn7mcB1vy">http://t.co/mFn7mcB1vy</a></p>&mdash; pepephone (@pepephone) <a href="https://twitter.com/pepephone/status/436461
658601713664">February 20, 2014</a></blockquote>

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/TwitterTest.php:21

4) WordPressTest::testOne
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Dave Ross: Optimize Image Files Like a Pro
+Dave Ross: Optimize Image Files Like a Pro

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/WordPressTest.php:8

FAILURES!
Tests: 72, Assertions: 343, Errors: 1, Failures: 4.
```

**Guzzle**
```php
1) CodepenTest::testAnonymous
GuzzleHttp\Exception\ClientException: Client error response [url] http://codepen.io/anon/details/QwPVNW [status code] 404 [reason phrase] Not Found

/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:89
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/Subscriber/HttpError.php:33
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/Event/Emitter.php:109
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/RequestFsm.php:91
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/RequestFsm.php:132
/www/yoda/vendor/embed/embed/vendor/react/promise/src/FulfilledPromise.php:25
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php:55
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/Message/FutureResponse.php:43
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/RequestFsm.php:135
/www/yoda/vendor/embed/embed/vendor/guzzlehttp/guzzle/src/Client.php:165
/www/yoda/vendor/embed/embed/src/RequestResolvers/Guzzle.php:97
/www/yoda/vendor/embed/embed/src/RequestResolvers/Guzzle.php:76
/www/yoda/vendor/embed/embed/src/Request.php:66
/www/yoda/vendor/embed/embed/src/Request.php:139
/www/yoda/vendor/embed/embed/src/Request.php:251
/www/yoda/vendor/embed/embed/src/Adapters/Adapter.php:91
/www/yoda/vendor/embed/embed/src/Adapters/Adapter.php:75
/www/yoda/vendor/embed/embed/src/Embed.php:100
/www/yoda/vendor/embed/embed/src/Embed.php:43
/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:32
/www/yoda/vendor/embed/embed/tests/CodepenTest.php:6

--

There were 4 failures:

1) ImagesBlacklistTest::testPlainText
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif
+https://avatars1.githubusercontent.com/u/377873?v=3&s=400

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/ImagesBlacklistTest.php:16

2) ImagesBlacklistTest::testPlainUrlMatch
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-https://assets-cdn.github.com/images/spinners/octocat-spinner-32.gif
+https://avatars1.githubusercontent.com/u/377873?v=3&s=400

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/ImagesBlacklistTest.php:31

3) TwitterTest::testOmitScript
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-<blockquote class="twitter-tweet"><p lang="es" dir="ltr">RT <a href="https://twitter.com/PabloHerreros">@PabloHerreros</a> Pepephone rompe la baraja - <a href="http://t.co/mFn7mcB1vy">http://t.co/mFn7mcB1vy</a></p>&mdash; pepephone (@pepephone) <a href="https://twitter.com/pepephone/status/436461
658601713664">February 20, 2014</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
+<blockquote class="twitter-tweet"><p lang="es" dir="ltr">RT <a href="https://twitter.com/PabloHerreros">@PabloHerreros</a> Pepephone rompe la baraja - <a href="http://t.co/mFn7mcB1vy">http://t.co/mFn7mcB1vy</a></p>&mdash; pepephone (@pepephone) <a href="https://twitter.com/pepephone/status/436461
658601713664">February 20, 2014</a></blockquote>

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/TwitterTest.php:21

4) WordPressTest::testOne
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Dave Ross: Optimize Image Files Like a Pro
+Dave Ross: Optimize Image Files Like a Pro

/www/yoda/vendor/embed/embed/tests/TestCaseBase.php:16
/www/yoda/vendor/embed/embed/tests/WordPressTest.php:8
```

**Comment by oscarotero** [comment]
I'm using the latest version of Guzzle (6.0) (installed by default with `composer require guzzlehttp/guzzle`)

And about the failing tests, it's very hard to keep all these tests in green, because the same url returns different info deppending of the machine that execute the code. For example, all tests in my local environment are pased, but not in travis (the result of the same request is different). I don't know the reason, maybe it's about the php configuration.

**Comment by younes0** [comment]
Oh! I see the failures now, due to major breaking change in 6.x.
I'll fix this.

**Comment by younes0** [comment]
Looks like Guzzle 6 has removed getEffectiveUrl()  : https://github.com/guzzle/guzzle/issues/1166

Maybe we could wait for 6.x support ?

**Comment by oscarotero** [comment]
We can create a `Embed\RequestResolvers\Guzzle5` and `Embed\RequestResolvers\Guzzle6` (or just Guzzle). What you think?

**Comment by younes0** [comment]
Done! 
Thanks

**Comment by oscarotero** [comment]
Please, can you rename the file Guzzle.php to Guzzle5.php? it's to keep psr-4 compatibility

**Comment by younes0** [comment]
my bad, done

**Comment by oscarotero** [comment]
Hi, can this be merged or is there anything else to do?
About the binary files problems, I think guzzle has events that can stop the download at any time, but I'm not sure.

**Comment by younes0** [comment]
I think you can merge even if there's this binary files download, since the main purpose IMHO of Guzzle is to allow Request mocking

**Comment by oscarotero** [comment]
Ok, thanks for the contribution :smile:

**Comment by younes0** [comment]
you're welcome :+1:

**Pull request merged**
