### PR TITLE
Fix for #62: YouTube 'TooManyRequests' 

### PR DESCRIPTION
**Pull request by slawus**
Hi!

I've managed to change library a little bit, so it may be used even if youtube.co returns 429 code. This fix should be backward compatible.

First of all ,I've added configuration for Request, where user can define all allowed http codes ($config['request']['allowedCodes']). By default i's only 200. 

```php
$config = [
    'request' => [
        'allowedCodes' => [ 200 ]
    ]
];
```

Secondary, I've changed priority of OEmbed providers (located in /src/Providers/OEmbed/), so they are used first, and if there is no provider for given url, Embed looks for url in webpage code. I've also created Youtube provider, which return correct OEmbed url. It was enough to make youtube work.

After this change, it turned out that Soundcloud provider was broken, and it was breaking tests (Embed wasn't using it, couse it was checking for OEmbed path in code, and nowadays  SoundCloud is providing one) so I've removed it.

Testing code for guys that had 429 problem (should be run via cli, with youtube link as first argument):

```php
<?php
ini_set('display_errors', '1');
ini_set('display_startup_errors', '1');

include '../src/autoloader.php';

if(!(isset($argv[1]))) {
    echo 'You must provide url as first argument.';
    die();
}

$url = $argv[1];
try {
    $info = Embed\Embed::create($url, [
	'request' => [ 'allowedCodes' => [200, 429]]
    ]);
    var_dump($info->title);
} catch (Exception $exception) {
    echo "EXCEPTION\n";
    echo "=========\n";
    echo $exception->getMessage()."\n";
    die();
}

```

I'm open for any sugestions.

### CODE REVIEW

**Comment by slawus** [comment]
As you can see build hasn't passed Youtube test in travis-ci, couse 429 code is not enabled by default. I can enable it in this test, if you think it is ok.

**Comment by oscarotero** [comment]
Hi.
Thanks for your great job. I cannot test 429 status code because youtube always returned 200 in my environments. But I have some doubs:
* Why change the oembed detection priority? The reason of search first in the html code is to avoid the library fails if the oembed provider is deprecated (the service changes the api, or the oembed endpoint, or whatever) because, supposedly, the url coming in the code is updated and more reliable.
* I'm not sure of the `request => allowCodes` setting, because it simply go on, doing the same things as if the code is 200. This works fine for youtube, because it has an oembed provider with all information, but I don't know if this can works fine with other sites that does not have this provider. Let's say an error page that Embed takes as good result, so the title may be something like "There are too many requests", and the image is a warning symbol taken from the html code. Maybe a better aproach is to create a special adapter (like the adapter created for files) to handle this errors. So this adapter can avoid the providers depending of html code (opengraph, html, etc) and try to get the information from safe sources (oembed, an external api, etc).
* Another aproach is simply create the Youtube429 adapter, to handle this specific case and let the rest of the services fail. If there's another service we can "rescue", we always can create another adapter for it.

**Comment by slawus** [comment]
Thanks for feedback :)! As you can't see how 429 response look like, i've made a [dump](http://pastebin.com/hE2xF0Tb).

* Actually, I've just found out that this change was unnecessary. After enabling 429 status code, Embed was returning "Youtube" as a title, instead of video's title. I was convinced, it's becouse 429 error page has it's own oembed link, which directs to wrong resource... something like that:
```html
<link rel="alternate" type="application/json+oembed" href="http://www.youtube.com/oembed?url=http://www.youtube.com">
```
But the truth is, that there was no oembed link at all (on 429 page). Since at that time, there was not YouTubes provider , OEmbed was not used, and title was extracted directly from html (or other provider). I will revert this change later.

* Your idea sounds really nice, but I guess it might be very tricky: most of errors will occure for both application and user, so library should return null in most of cases (as it was done till now). The only error we have to manage with (for now) is 429 from youtube. Making whole new adapter might be an overkill.. but i agree that it's much better solution (it doesn't allow 429 for other services than Youtube).

* If I understand correctly, this would have to be hardcoded into Embed::check, which doesn't sound right.

So I have 2 proposals:

* after getting error (i.e statusCode != 200), library will look for Adapter in namespace "Embed\Adapters\Error", adapter should have same name as host in request (in this case Youtube).

or

* move request validation from Embed::create, into adapters. Since all of existing adapters inherits from Embed\Adapter\Adapter, it will be enough to implement it into constructor of that class (so when status code is different then 200 it doesn' do anything / throw exception). Then, we can create Embed/Adapter/Youtube, which perform process, even if status code will be equal 429.

Personally, I would choose the second option. What do you think? :)

**Comment by oscarotero** [comment]
If I understand correctly, you are saying to move (or remove) this block: https://github.com/oscarotero/Embed/blob/master/src/Embed.php#L20. So all adapters must check not only if the url match with the patterns but also whether the url returns 200.
So we can create a Youtube adapter that check also if the code is 429 to load only the oembed provider.
I think it's a good solution.

**Comment by oscarotero** [comment]
Hi. I didn't merge this, but used some of your work to fix this issue. In the new release the tooManyRequests should be fixed.
Thank you :+1:

**Comment by slawus** [comment]
Ok, great to hear! I was planning to write fix, just didn't have enough time in last 2 weeks :/ Thanks again for the lib :)

**Comment by tmli3b3rm4n** [comment]
awesome news!! 


     On Monday, August 17, 2015 11:12 AM, slawus <notifications@github.com> wrote:
   

 Ok, great to hear! I was planning to write fix, just didn't have enough time in last 2 weeks :/ Thanks again for the lib :)—

**Pull request closed without merging**
