### PR TITLE
Enforced type of suffixes to array

### PR DESCRIPTION
**Pull request by xyNNN**
When the runtime including of the suffixes (`self::$public_suffix_list = include __DIR__.'/../resources/public_suffix_list.php';`) list don't work out the method return value is a boolean. So the in_array method will throw an error. Why this is implemented as a include instead of a private property or constant value?

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi, thanks for this. I think this should be fixed in the `getSuffixes()` function. If you make this change, I'll merge the PR.

**Comment by xyNNN** [comment]
I've changed the implementation. When the including fails due to what ever reason the return value is a boolean, so we need so save it in a temporary variable and based on this value we have to decide.

**Comment by xyNNN** [comment]
It would be awesome if you could merge this and tag a new release :) thanks!

**Comment by oscarotero** [comment]
The problem is that you may want to do not use suffixes at all, and there's not a way to config this. I was thinking in something like this:

```php
    private static function getSuffixes()
    {
        if (self::$public_suffix_list === null) {
            self::$public_suffix_list = (array) include __DIR__.'/../resources/public_suffix_list.php';
    	}
        return self::$public_suffix_list;
    }
```

**Comment by oscarotero** [comment]
Thanks!

**Comment by xyNNN** [comment]
Thanks @oscarotero - It's possible that you could tag a new release?

**Comment by oscarotero** [comment]
Done: https://github.com/oscarotero/Embed/releases/tag/v3.3.8

**Pull request merged**
