### PR TITLE
Updated include of public suffixes

### PR DESCRIPTION
**Pull request by xyNNN**
I've encountered another problem. When you have restricted your include paths via your php.ini your're getting a warning when you using this library. To solve this I've added the @ operator and enforced the return value of this include to be an array.

### CODE REVIEW

**Comment by oscarotero** [comment]
Ok, thanks

**Comment by xyNNN** [comment]
Thank you mate, could you create also a patch release so I don't have to require the dev-master? ;) Thanks mate!

**Comment by xyNNN** [comment]
Have you some new informations for me? Thanks mate! :) Can I support you in some topic?

**Comment by oscarotero** [comment]
Sorry, I missed this. New version released.

**Pull request merged**
