### PR TITLE
Sassmeister support

### PR DESCRIPTION
**Pull request by mburtscher**
Implements #49

### CODE REVIEW

**Comment by oscarotero** [comment]
Yeah!

But I have a suggestion: the "official" embed code looks like this:

```html
<p class="sassmeister" data-gist-id="1122e441f0434ec6eb2a" data-height="480" data-theme="tomorrow"><a href="http://sassmeister.com/gist/1122e441f0434ec6eb2a">Play with this gist on SassMeister.</a></p><script src="http://cdn.sassmeister.com/js/embed.js" async></script>
```

Maybe the code returned should respect the same format, instead directly the iframe. So, future changes in their javascript code are reflected. What do you think?

And one last thing: can you provide a test for this, please?

thank you :)

**Comment by mburtscher** [comment]
From the library POV I think it would be better to generate the "official embed code". But from the consumer side I'd prefer that all adapters generate a similar embed code (e.g. the iframe as outer most element) if possible.

__Why?__ In our product for example we have an activity stream like on social networks. We parse user input and attach meta information to a user's post when the embed library provides such information. It's kinda hard to predict the outcome if some adapters generate `<iframe>`s and others generate `<p>` tags with additional JS. Especially if you don't enable each adapters individually.

Don't know which solution to choose since neither of them is "better".

**Comment by oscarotero** [comment]
The problem with generating custom embed code is maintenance.
A real example is google maps. For some time, this code worked fine (https://github.com/oscarotero/Embed/blob/dc44f698104fd34d81fe66136be1a809b6357f21/src/Adapters/Google.php#L36) (use an iframe with the same url appended output=embed), but now that stopped working, so I had to remove it.
Generating the same code that you can copy and paste from the original site is the best choice because you're delegating the code maintenance to its owners and don't have to check once in a while whether the code still working.
There are a lot of services providing scripts to generate the iframe. For example, twitter or facebook, so it's a common practice.

**Comment by mburtscher** [comment]
That's fine, so lets do it that way. I'll update this PR in a few days.

**Comment by oscarotero** [comment]
Great! thanks so much :+1:

**Comment by mburtscher** [comment]
@oscarotero Have you seen my update on this?

**Comment by oscarotero** [comment]
Thanks! :+1:

**Pull request merged**
