### PR TITLE
Add image weight and date using the Curl headers

### PR DESCRIPTION
**Pull request by edhelas**
Theses information are took directly from the existing Curl request headers (so without any network performances impact).

### CODE REVIEW

**Comment by edhelas** [comment]
The content-length and last-modified HTTP headers are actually not mandatory. But is it something that can still be added ?

**Comment by oscarotero** [comment]
I suspect this is a feature required in your implementation, isn't? I think it can be fine to get the http headers of all images, but why only last-modified and content-head and not others?

Maybe a better approach is to allow to configure this, but I have to think a good way to do it.
Other solution is create your own imageinfo implementation (extending the default) and use it.

**Comment by edhelas** [comment]
Well I don't have a specific need for now but it would be nice to have more information related to the file itself (to choose to download it or not for example). Having something configurable can be also interesting.

**Comment by oscarotero** [comment]
I'm agree that having more details about the http request should be fine, but the purpose of this array is provide information about the image itself, not the http connection.
I created an issue #123 to find a way to store and access to this information without mix http data with content data.
Thanks anyway for the idea :smiley:

**Comment by edhelas** [comment]
I'm closing this pull request and move to #123 ;) Thanks again !

**Pull request closed without merging**
