### PR TITLE
Readme edit. rawurlencode instead of urlencode. Add bt:pubDate

### PR DESCRIPTION
**Pull request by MrHexagon**
- Edit readme to read publishedTime instead of publishedDate
- Use rawurlencode instead of urlencode.
- Add bt:pubDate to keys in getPublishedTime()

### CODE REVIEW

**Comment by oscarotero** [comment]
Hi, thanks for this contribution.
The problem with `rawurlencode` is it makes the google plus url fail:
https://travis-ci.org/oscarotero/Embed/jobs/322630639#L622

**Comment by MrHexagon** [comment]
oh ok :( thanks for having a look

**Comment by oscarotero** [comment]
Ok, I've seen this issue https://github.com/oscarotero/Embed/issues/255
Do you think there's a way to detect automatically which method can be used in each case?

**Comment by Vinorcola** [comment]
The problem here was due to a bad test. The `+` must be encoded into the URL into `%2B`

**Pull request closed without merging**
