### PR TITLE
Better space encoding in Url

### LINKED ISSUE #255: Encoded characters in image URLs have wrong decoding
Hello,

I'm trying to use your library in a website which there is an image like this url:

`http://www.company.com/Uploads/product_image%20copy.png`

But when i try to reach images i saw that image URL is like:

`http://www.company.com/Uploads/product_image+copy.png`

So it changed `%20` to `+` character. Its wrong.

### PR DESCRIPTION
**Pull request by Vinorcola**
Closes #255 
Replaces https://github.com/oscarotero/Embed/pull/259 that was incomplete (Google Plus)

The problem with GooglePlus was due to the `+` no being encoded into `%2B`
This Pull Request fix this.

However, I still have an issue with the title in some test, I'll may need some help to fix that.

```
1) Embed\Tests\GoogleTest::testMap
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Tordoia, A Coruña
+Tordoia,+A+Coruña
```

The title will have to be reviewed (transform + into space).

### CODE REVIEW

**Comment by Vinorcola** [comment]
`urlencode/urldecode` are meant to be used for query params (Mime type `application/x-www-form-urlencoded`)

Urls are meant to be encoded with `rawurlencode/rawurldecode`
Now, the query params being part of the URL, the (encoded) query param must be encoded into the URL. So, the `+` in the URL must be encoded into `%2B`.

Check https://stackoverflow.com/questions/1634271/url-encoding-the-space-character-or-20

**Comment by oscarotero** [comment]
Sounds good. Thanks!

**Comment by Vinorcola** [comment]
@oscarotero There is still the issue with the Google title.
Can we change `+` into spaces in Google titles specifically?

**Comment by oscarotero** [comment]
@Vinorcola We have some manual replacements here: https://github.com/Vinorcola/Embed/blob/master/src/Http/Url.php#L668 so we can add the `+`.

**Comment by Vinorcola** [comment]
@oscarotero Sorry, I wasn't clear enough. I meant for the resource's `title` attribute, not the URL.

I still have a failing test:

```
1) Embed\Tests\GoogleTest::testMap
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
-Tordoia, A Coruña
+Tordoia,+A+Coruña
```
Which is linked to this line:
https://github.com/oscarotero/Embed/blob/master/tests/GoogleTest.php#L12

I think the test is good, and the problem comes from the `title` generation.

I don't kown how the resource `title` is set in that case and if we can change the explicitly replace `+` into spaces in the `title` attribute of a Google Map resource.

**Comment by oscarotero** [comment]
The title is get from the url: https://github.com/oscarotero/Embed/blob/master/src/Providers/Api/GoogleMaps.php#L50

**Pull request merged**
