### PR TITLE
Load all JSON-LD data

### PR DESCRIPTION
**Pull request by brianlmoon**
The LinkedData class was only grabbing the first application/ld+json
script tag found in the DOM. It now finds them all and makes them
all available via the getAll method. Additionally, it inspects the
mainEntityOfPage property of the json nodes and if a match is found
with the request URI, that node is assigned as the default node
rather than the first node found.

### CODE REVIEW

**Comment by oscarotero** [comment]
Thanks!
Running the tests, it seems that PHP 8.1 treats some characters in JSON-LD differently.

**Comment by brianlmoon** [comment]
I will have a look at 8.1, thanks.

**Comment by brianlmoon** [comment]
Yep, the default flags for [html_entity_decode changed in PHP 8.1](https://www.php.net/html_entity_decode#refsect1-function.html-entity-decode-changelog)
```
 flags changed from ENT_COMPAT to ENT_QUOTES | ENT_SUBSTITUTE | ENT_HTML401. 
```

**Comment by brianlmoon** [comment]
Tested on 8.0 and 8.1. I don't have 7.4 anywhere around to test with though. Hopefully it passes OK as well with this change.

**Comment by oscarotero** [comment]
thanks! the tests keep failing but it's due a different issue.

**Pull request merged**
