### PR TITLE
Update Test according sad reality

### PR DESCRIPTION
**Pull request by zyuhel**
#98

### CODE REVIEW

**Comment by zyuhel** [comment]
interesting question, should things like "- Find & Share on GIPHY" be removed somewhere in providers?

**Comment by oscarotero** [comment]
I don't think Embed should modify the information, just fix it if it's broken.
Checking the giphy adapter, I think it can be removed. It was created originally to fix the code returned by oembed (that didn't work correctly). But now it's working fine, so there's no need to maintain it.

**Comment by zyuhel** [comment]
Remove it is pretty original approach. Less code less bugs :)

**Comment by oscarotero** [comment]
Great :+1:

**Pull request merged**
