### PR TITLE
WIP - add PHP 8 support

### PR DESCRIPTION
**Pull request by sminnee**

### CODE REVIEW

**Comment by sminnee** [comment]
Looks like this will be blocked by https://github.com/phpspec/prophecy/pull/497

**Comment by sminnee** [comment]
Once https://github.com/oscarotero/html-parser/pull/1 is merged and tagged I'll look at this again.

**Comment by stephanvierkant** [comment]
It is tagged! https://github.com/oscarotero/html-parser/releases/tag/v0.1.5

**Comment by sminnee** [comment]
Good to know! This is still disrupted by schrodinger's test suite - see #382

**Comment by oscarotero** [comment]
Some time ago, I've removed all test files and regenerated again and now seems like it works fine. At least in my computer and in TravisCI. So maybe we can close #382

**Comment by strarsis** [comment]
Part of this PR has been fixed by a PR based on fresh master (`match` named function): https://github.com/oscarotero/Embed/pull/394

**Comment by oscarotero** [comment]
Yes, I think we can close this PR and fix PHP8 issues in different PR.
Thanks anyway 👍

**Comment by sminnee** [comment]
Cheers!

**Pull request closed without merging**
