### PR TITLE
Images URLs blacklist

### PR DESCRIPTION
**Pull request by Soullivaneuh**
This PR is related to #54.

Here, the todo list:

 - [x] Remove empty URLs from images list
 - [x] Implement an `imagesBlacklist` options to filter images urls (see https://github.com/oscarotero/Embed/issues/54#issuecomment-85419821)
 - [x] Update the doc according to the new option
 - [x] Write some tests

Don't hesitate to review my code. :+1:

### CODE REVIEW

**Comment by Soullivaneuh** [comment]
@oscarotero A question about your `Url` class.

If I have the following url: http://www.lopinion.fr/sites/nb.com/files/2015/01/logo-o-default_0.png?p

Is the `match` method should return true with those pattern ?

 * `http://www.lopinion.fr/sites/nb.com/files/2015/01/logo-o-default_0.png?p`
 * `http://www.lopinion.fr/sites/nb.com/files/2015/01/logo-o-default_0.png`

Seems not for me. Maybe a conflict with the `?` symbol?

**Comment by Soullivaneuh** [comment]
Please note actual failed test are not caused by my PR. Same errors on master.

**Comment by oscarotero** [comment]
Hi. Yes, I see there are some problems maybe the match method needs to be fixed.

To use `?` in the pattern, it should be escaped: `http://www.lopinion.fr/sites/nb.com/files/2015/01/logo-o-default_0.png\\?p`.

The special characters `^` and `$` are inserted by default so they don't have to be defined again (https://github.com/oscarotero/Embed/blob/master/src/Url.php#L59)

I prefer use this simple way (just with ? and *) because is the same format I see in some oembed implementations and it's flexible and easy enought for this purpose.

And about the failed tests, the urls that I use for testing sometimes do not return the espected result. Sometimes the website changes the images, or redirect to https, etc, and this requires to change the tests occasionally.

**Comment by Soullivaneuh** [comment]
> The special characters ^ and $ are inserted by default so they don't have to be defined again (https://github.com/oscarotero/Embed/blob/master/src/Url.php#L59)

I think is especially the "problem".

How can I do if I want to ignore image that **only** begin by `http://example.com/bad/` or **only** terminated by **bad-image.png**? I don't think we can with this situation, isn't it?

**Comment by oscarotero** [comment]
> How can I do if I want to ignore image that only begin by http://example.com/bad/ or only terminated by bad-image.png? I don't think we can with this situation, isn't it?

Begin: `http://example.com/bad/*`
Terminated: `*bad-image.png`

**Comment by Soullivaneuh** [comment]
Ok you win. :)

**Comment by Soullivaneuh** [comment]
I did both match and in_array method for image filter.

**Comment by Soullivaneuh** [comment]
I did both match and in_array method for image filter.

Some people would only specified complete URL with maybe some `?` characters. Will work with those both solutions.

I just added the test, the documentation is OK.

I think this PR is ready to merge! :+1: 

Feel free to review it.

**Comment by oscarotero** [comment]
Thanks so much, great job!
Maybe for large blacklists a more optimized solution should be required (converts the patterns to regex only once, for example). But for now, this solution is fine. :smile_cat:

**Comment by Soullivaneuh** [comment]
@oscarotero optimized where? You talk about the `in_array` function? Maybe could be optimized with keys playing but I don't really know how.

For the patterns, I think developers won't use a huge blacklist array but will play with the regexp isn't it? :)

Another question: When should I see a new stable version with this integrated PR? Thanks.

**Comment by oscarotero** [comment]
Sorry, I was wrong, the code is right. I mean each time the `$url->match()` is executed in the `array_filter`, the function creates new regex with the patterns, but they are created by each image found, not by each url in the blacklist.
And yes, developers love regex :smile: 
I will release the new version in a few minutes, just need to fix the failing tests and other bit change.

**Comment by Soullivaneuh** [comment]
Ok glad to hear the same song! ;)

Thanks.

**Comment by oscarotero** [comment]
You got it https://github.com/oscarotero/Embed/releases/tag/v2.2

**Comment by Soullivaneuh** [comment]
:+1:

**Pull request merged**
