### PR TITLE
Fixed Bambuser test

### PR DESCRIPTION
**Pull request by zyuhel**
Fixed Bambuser test, service returns https now. #85

### CODE REVIEW

**Comment by zyuhel** [comment]
Interesting behaviour. test on travis works correctly, local machine tests return https.

**Comment by oscarotero** [comment]
Yeah, there're some cases of tests passing in local but failing in travis and viceversa. I don't know the reason, maybe it's a server side thing and deppending of the origin of the request, returns different responses. I've tried to fix this several times but I couldn't

**Comment by zyuhel** [comment]
About Bambuser if endpoint will be defined using https instead of http, may be it will return https embeds always?
Behaviour like this exists in Dailymotion

**Comment by oscarotero** [comment]
Yes, that's can be a reason, but it's difficult to solve. The Dailymotion endpoint is defined in the html code (using a `<link rel="alternate" type="application/json+oembed">` tag) so there's not an oembed provider in Embed, and always returns a http endpoint (not https), even if the url is https.

Maybe a good way to solve this issue is to provide two different results to the test (one http, and other https), because both results are correct. I'd like to avoid this but I cannot think of anything else to fix it.

**Comment by zyuhel** [comment]
I was talking about dailymotion endpoint generally. if it called from https it https else it is http.
may i make a pull request to see will it return https to travis?

**Comment by oscarotero** [comment]
Yes, no problem.

**Comment by zyuhel** [comment]
So with changed endpoint it pass bambuser test both locally and on travis :)

**Comment by oscarotero** [comment]
Great!. Can I merge this?

**Comment by zyuhel** [comment]
Yes of course.
Unrelated question, if i write a couple of providers should i keep them separate or merge in master repo?

**Comment by oscarotero** [comment]
master is fine. Currently there's no a `develop` branch.

**Pull request merged**
