### PR TITLE
Twitter detector

### PR DESCRIPTION
**Pull request by dftd**
https://github.com/oscarotero/Embed/issues/364

A free Twitter API key is required. You need to add the Bearer like this:

```php
$embed->setSettings([
    'twitter:token' => 'asdf'
]);
```

Available data is: description, image, authorName, authorUrl, publishedTime. Title is just "Tweet by {name}".

### CODE REVIEW

**Comment by dftd** [comment]
I am yet not sure how to fetch images from Tweets which contains URLs.

**Comment by oscarotero** [comment]
Why we have to do that? The images urls returned by the API, right?

**Comment by dftd** [comment]
If a regular image is uploaded, API returns it's url. But not when someone tweets a link, even though Twitter does show the image from that site.
Not sure is it needed to bother with it here though. I'll probably implement it for myself, by searching for links in Tweet description, fetching the first link with this library and using it's image.

**Comment by oscarotero** [comment]
I think Embed library should show only what Twitter gives. But using regex to capture images that are not provided by Twitter API looks a bit hacky and hard to maintain. If anyone wants to get that, it could be implemented outside Embed.

**Comment by dftd** [comment]
Yeah, as I said...
I think this should be ready to merge now? Only thing I didn't add, not sure is it required, is some kind of check for valid Twitter url.

**Comment by oscarotero** [comment]
I guess it's not needed. If the url is not valid, Twitter API would return nothing.
I'll update the tests and will release a version soon.
Thanks for your work!

**Pull request merged**
